package com.miaoshaproject.dao;

import com.miaoshaproject.dataobject.UserpasswordDo;

public interface UserpasswordDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Fri Apr 24 14:27:12 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Fri Apr 24 14:27:12 CST 2020
     */
    int insert(UserpasswordDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Fri Apr 24 14:27:12 CST 2020
     */
    int insertSelective(UserpasswordDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Fri Apr 24 14:27:12 CST 2020
     */
    UserpasswordDo selectByPrimaryKey(Integer id);
    UserpasswordDo selectByUserId(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Fri Apr 24 14:27:12 CST 2020
     */
    int updateByPrimaryKeySelective(UserpasswordDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Fri Apr 24 14:27:12 CST 2020
     */
    int updateByPrimaryKey(UserpasswordDo record);
}